jdk: openjdk8
language: groovy

branches:
  only:
  - /.*/

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_80297b79dae4_key -iv $encrypted_80297b79dae4_iv
          -in gradle.properties.enc -out gradle.properties -d;
    fi

script: ./buildViaTravis.sh
